## 配置端口
server:
  port: 8080

## mybatis
mybatis:
  type-aliases-package: com.sbl.model

## 配置DB
spring:
  datasource.url: jdbc:mysql://129.28.193.110:3306/aqua
  datasource.username: nat
  datasource.password: nat090401
  datasource.driver-class-name: com.mysql.cj.jdbc.Driver