## 配置端口
server:
  port: 8080

## mybatis
mybatis:
  type-aliases-package: com.sbl.model

spring:
  ## 配置DB
  datasource:
    url: jdbc:mysql://129.28.193.110:3306/aqua
    username: nat
    password: nat090401
    driver-class-name: com.mysql.cj.jdbc.Driver

  ## 配置jpa
  jpa:
    properties.hibernate.hbm2ddl.auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

  ## 配置redis
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 192.168.4.14
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制） 默认 8
    lettuce.pool.max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
    lettuce.pool.max-wait: -1
    # 连接池中的最大空闲连接 默认 8
    lettuce.pool.max-idle: 8
    # 连接池中的最小空闲连接 默认 0
    lettuce.pool.min-idle: 0